# config/account_ids.yaml
# NMDose 시스템 사용자 정의 및 역할 기반 권한 정책

# 시스템 내 논리적 수퍼유저: 설정 변경 및 관리자 권한 보유자
superuser:
  id: nmdose_super_user      # nmdose 프로그램 내 설정 변경 권한자 (PostgreSQL 슈퍼유저 아님)
  description: >
    NMDose 시스템의 구성 변경, 설정 파일 관리, 고급 기능 접근을 허용합니다.
    PostgreSQL에서 superuser 권한은 없으며, 일반 계정으로 DB에 접속합니다.
    프로그램 내에서 관리자 권한으로 인식됩니다.

# 애플리케이션 사용자: 일반 사용자가 시스템을 사용하는 계정
users:
  - id: nmdose_user
    description: >
      NMDose 애플리케이션 사용을 위한 기본 계정입니다.
      PostgreSQL에는 일반 사용자로 등록되며,
      nmdose 데이터베이스의 rpacs 및 nmdose 스키마에 접근합니다.
    database: nmdose
    schemas:
      - name: rpacs
        privileges: [USAGE, SELECT, INSERT, UPDATE, DELETE]
      - name: nmdose
        privileges: [USAGE, SELECT, INSERT, UPDATE, DELETE]
